# Generated by Django 4.0.6 on 2022-07-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='short_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
