# Generated by Django 4.0.6 on 2022-07-30 09:36

from django.db import migrations, models
import promises.models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0002_promise_short_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='promise',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='short_link',
            field=models.CharField(default=promises.models.Promise.generate_link, max_length=200),
        ),
    ]
